# settings
title: Panthera
description: Panthera is a genus in the Felidae family.
url: "https://tracertokenn.github.io"
baseurl: "/panthera"
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
github:
  is_project: true
  repository_url: "https://github.com/tracertokenn/panthera"
