# settings
title: Panthera
description:
url: "https://tracertokenn.github.io"
baseurl: "/panthera"
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

github:

is_project_page: false
